name: Python Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Настраиваем Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. Устанавливаем зависимости и браузеры Playwright
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    # 4. Запускаем тесты Playwright в headless режиме
    - name: Run tests with pytest
      run: pytest --alluredir=allure-results
      env:
        PLAYWRIGHT_HEADLESS: "1"

    # 5. Устанавливаем Java 17 для Allure
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # 6. Скачиваем и устанавливаем Allure CLI
    - name: Install Allure CLI
      run: |
        curl -sSL https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz | tar -xz
        sudo mv allure-2.34.1/bin/allure /usr/local/bin/allure

    # 7. Проверяем версию Allure
    - name: Check Allure version
      run: allure --version

    # 8. Генерируем HTML-отчёт Allure
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    # 9. Деплоим отчёт на GitHub Pages
    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
