name: Run Playwright Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Run pytest with Allure
      run: |
        pytest --alluredir=allure-results

    - name: Install Allure
      run: |
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.34.1.tgz -O allure.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.34.1/bin/allure /usr/local/bin/allure

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
