name: Python Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Настраиваем Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # 3. Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps

    # 4. Запускаем тесты Playwright в headless режиме и генерируем Allure результаты
    - name: Run tests with pytest
      run: |
        pytest --headless --alluredir=allure-results

    # 5. Устанавливаем Allure CLI через готовый Action
    - name: Setup Allure CLI
      uses: allure-framework/allure-action@v2

    # 6. Генерируем HTML-отчёт Allure
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    # 7. Деплой отчёта на GitHub Pages
    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
